import { IProduct } from "@interfaces/product";

export interface IData {
  discounts: IProduct[];
  popular: IProduct[];
}

export const data: IData = {
  discounts: [
    {
      name: "Limon con semilla",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/lemon.png",
      price: 26.82,
      priceWithoutDiscount: 39.9,
      discountPercentage: 32,
      weightUnit: "kg",
    },
    {
      name: "Tomate",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/tomato.png",
      price: 21.79,
      priceWithoutDiscount: 32.9,
      discountPercentage: 32,
      weightUnit: "kg",
    },
    {
      name: "Aguacate Hass",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/avocado.png",
      price: 56.8,
      priceWithoutDiscount: 69.9,
      discountPercentage: 18,
      weightUnit: "kg",
    },
    {
      name: "Nopal limpio",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/nopal.png",
      price: 25.8,
      priceWithoutDiscount: 29.9,
      discountPercentage: 13,
      weightUnit: "kg",
    },
    {
      name: "Tomate verde sin cascara",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/green-tomato.png",
      price: 22.89,
      priceWithoutDiscount: 24.9,
      discountPercentage: 9,
      weightUnit: "kg",
    },
    {
      name: "Coca-Cola Sin Azucar",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/coke-zero.png",
      price: 26,
      priceWithoutDiscount: 28,
      discountPercentage: 7,
      weightUnit: "kg",
    },
    {
      name: "Coca-Cola",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/coke.png",
      price: 12.9,
      priceWithoutDiscount: 14,
      discountPercentage: 7,
      weightUnit: "l",
    },
  ],
  popular: [
    {
      name: "San Rafael pechuga de pavo",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/balance-turkey.png",
      price: 62.5,
      weight: 250,
      weightUnit: "gr",
    },
    {
      name: "Bimbo Pan Blanco Grande",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/bread-bimbo.png",
      price: 38.9,
      weight: 680,
      weightUnit: "gr",
    },
    {
      name: "Mc Cormick Mayonesa",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/mayo.png",
      price: 48.5,
      weight: 507,
      weightUnit: "gr",
    },
    {
      name: "Colgate Pasta Dental Triple Familiar 2 U",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/colgate.png",
      price: 38.5,
      weight: 125,
      weightUnit: "ml",
    },
    {
      name: "Huevos San Juan",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/eggs.png",
      price: 37.5,
      weight: 18,
      weightUnit: "u.",
    },
    {
      name: "Fabuloso Limpiador Antibacterial",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/fabuloso.png",
      price: 26,
      priceWithoutDiscount: 28,
      discountPercentage: 7,
      weight: 2,
      weightUnit: "l",
    },
    {
      name: "Coca-Cola",
      desc: "Fugiat in consequat non commodo elit deserunt esse.Reprehenderit culpa tempor ut commodo cupidatat mollit do do.",
      imageURL: "/assets/images/coke.png",
      price: 12.9,
      priceWithoutDiscount: 14,
      discountPercentage: 7,
      weight: 600,
      weightUnit: "ml",
    },
  ],
};
